/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author tiago
 */
public class AppointmentPlace extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public AppointmentPlace() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelAppointment = new javax.swing.JLabel();
        LabelId = new javax.swing.JLabel();
        LabelClient = new javax.swing.JLabel();
        LabelService = new javax.swing.JLabel();
        LabelValue = new javax.swing.JLabel();
        LabelData = new javax.swing.JLabel();
        LabelHour = new javax.swing.JLabel();
        LabelNote = new javax.swing.JLabel();
        TextId = new javax.swing.JTextField();
        TextClient = new javax.swing.JComboBox<>();
        TextService = new javax.swing.JComboBox<>();
        TextValue = new javax.swing.JTextField();
        TextFormatedData = new javax.swing.JFormattedTextField();
        TextFormatedHour = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextObservacao = new javax.swing.JTextArea();
        ButtonSchedule = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSchedules = new javax.swing.JTable();
        LabelAgendaBackgroundWindown = new javax.swing.JLabel();
        LabelAppointmentBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelAppointment.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        LabelAppointment.setForeground(new java.awt.Color(255, 255, 255));
        LabelAppointment.setText("Appointment");
        getContentPane().add(LabelAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 240, 60));

        LabelId.setForeground(new java.awt.Color(255, 255, 255));
        LabelId.setText("Id");
        getContentPane().add(LabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        LabelClient.setForeground(new java.awt.Color(255, 255, 255));
        LabelClient.setText("Client");
        getContentPane().add(LabelClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        LabelService.setForeground(new java.awt.Color(255, 255, 255));
        LabelService.setText("Service");
        getContentPane().add(LabelService, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        LabelValue.setForeground(new java.awt.Color(255, 255, 255));
        LabelValue.setText("Value $");
        getContentPane().add(LabelValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

        LabelData.setForeground(new java.awt.Color(255, 255, 255));
        LabelData.setText("Data");
        getContentPane().add(LabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, -1));

        LabelHour.setForeground(new java.awt.Color(255, 255, 255));
        LabelHour.setText("Hour");
        getContentPane().add(LabelHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        LabelNote.setForeground(new java.awt.Color(255, 255, 255));
        LabelNote.setText("Note");
        getContentPane().add(LabelNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        TextId.setEditable(false);
        TextId.setText("0");
        TextId.setToolTipText("");
        TextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIdActionPerformed(evt);
            }
        });
        getContentPane().add(TextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 280, 40));

        getContentPane().add(TextClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 280, 40));

        TextService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banho", "Banho e tosa", "Tosa", "" }));
        getContentPane().add(TextService, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 280, 40));

        TextValue.setText("0");
        TextValue.setToolTipText("");
        TextValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValueActionPerformed(evt);
            }
        });
        getContentPane().add(TextValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 280, 40));

        TextFormatedData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        getContentPane().add(TextFormatedData, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 280, 40));

        TextFormatedHour.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        getContentPane().add(TextFormatedHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 280, 40));

        TextObservacao.setColumns(20);
        TextObservacao.setRows(5);
        jScrollPane2.setViewportView(TextObservacao);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 610, 280));

        ButtonSchedule.setBackground(new java.awt.Color(60, 233, 106));
        ButtonSchedule.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ButtonSchedule.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSchedule.setText("Schedule");
        ButtonSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonScheduleActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 610, 50));

        TableSchedules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Client", "Service", "Value", "Data", "Hour", "Note"
            }
        ));
        jScrollPane1.setViewportView(TableSchedules);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 1120, 330));

        LabelAgendaBackgroundWindown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(LabelAgendaBackgroundWindown, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1000));

        LabelAppointmentBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Background_Appointment.jpeg"))); // NOI18N
        getContentPane().add(LabelAppointmentBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdActionPerformed

    private void ButtonScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonScheduleActionPerformed

    private void TextValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentPlace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSchedule;
    private javax.swing.JLabel LabelAgendaBackgroundWindown;
    private javax.swing.JLabel LabelAppointment;
    private javax.swing.JLabel LabelAppointmentBackground;
    private javax.swing.JLabel LabelClient;
    private javax.swing.JLabel LabelData;
    private javax.swing.JLabel LabelHour;
    private javax.swing.JLabel LabelId;
    private javax.swing.JLabel LabelNote;
    private javax.swing.JLabel LabelService;
    private javax.swing.JLabel LabelValue;
    private javax.swing.JTable TableSchedules;
    private javax.swing.JComboBox<String> TextClient;
    private javax.swing.JFormattedTextField TextFormatedData;
    private javax.swing.JFormattedTextField TextFormatedHour;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextArea TextObservacao;
    private javax.swing.JComboBox<String> TextService;
    private javax.swing.JTextField TextValue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
