/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author tiago
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelBackgroundMainMenu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuRegistration = new javax.swing.JMenu();
        MenuItemClient = new javax.swing.JMenuItem();
        MenuItemService = new javax.swing.JMenuItem();
        MenuItemUser = new javax.swing.JMenuItem();
        MenuOperation = new javax.swing.JMenu();
        MenuItemAppoiment = new javax.swing.JMenuItem();
        MenuReport = new javax.swing.JMenu();
        MenuItemReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelBackgroundMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Background_PetShopMenuMain.jpg"))); // NOI18N
        getContentPane().add(LabelBackgroundMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 1000));

        MenuRegistration.setText("registration");
        MenuRegistration.setActionCommand("Cadastro  ");
        MenuRegistration.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N

        MenuItemClient.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        MenuItemClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/cliente32-icon.png"))); // NOI18N
        MenuItemClient.setText("  Client");
        MenuItemClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemClientActionPerformed(evt);
            }
        });
        MenuRegistration.add(MenuItemClient);

        MenuItemService.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        MenuItemService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/Dog-print-100.png"))); // NOI18N
        MenuItemService.setText("  Service");
        MenuRegistration.add(MenuItemService);

        MenuItemUser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        MenuItemUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/usuario32-icon.png"))); // NOI18N
        MenuItemUser.setText("  User");
        MenuRegistration.add(MenuItemUser);

        jMenuBar1.add(MenuRegistration);

        MenuOperation.setText("  Operation  ");
        MenuOperation.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N

        MenuItemAppoiment.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        MenuItemAppoiment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/agenda32-icon.png"))); // NOI18N
        MenuItemAppoiment.setText("Appointment");
        MenuOperation.add(MenuItemAppoiment);

        jMenuBar1.add(MenuOperation);

        MenuReport.setText("  Report  ");
        MenuReport.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N

        MenuItemReport.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        MenuItemReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/relatorioTrabalho32-icon.png"))); // NOI18N
        MenuItemReport.setText("Work");
        MenuItemReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemReportActionPerformed(evt);
            }
        });
        MenuReport.add(MenuItemReport);

        jMenuBar1.add(MenuReport);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemClientActionPerformed

    private void MenuItemReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelBackgroundMainMenu;
    private javax.swing.JMenuItem MenuItemAppoiment;
    private javax.swing.JMenuItem MenuItemClient;
    private javax.swing.JMenuItem MenuItemReport;
    private javax.swing.JMenuItem MenuItemService;
    private javax.swing.JMenuItem MenuItemUser;
    private javax.swing.JMenu MenuOperation;
    private javax.swing.JMenu MenuRegistration;
    private javax.swing.JMenu MenuReport;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
